COPY sys_log_ast to '/tmp/slaBackup.sql';
COPY sys_definition_alarm_static to '/tmp/sdasBackup.sql';
COPY sys_definition_alarm_dynamic to '/tmp/sdadBackup.sql';
COPY sys_definition_alarm_top_worst to '/tmp/sdatwBackup.sql';

SET statement_timeout = 0;
SET client_encoding = 'SQL_ASCII';
SET standard_conforming_strings = off;
SET check_function_bodies = false;
SET client_min_messages = warning;
SET escape_string_warning = off;
SET search_path = public, pg_catalog;

TRUNCATE TABLE sys_log_ast;
INSERT INTO sys_log_ast VALUES ((select date ( now() )  - 2) || ' 18:21:16', 'Info', 'Trending&Aggregation_TU', 'Data Collect', 'PROCESS : Start	collecting files', 'support_1', '');
INSERT INTO sys_log_ast VALUES ((select date ( now() )  - 2) || ' 18:21:17', 'Info', 'Trending&Aggregation_TU', 'Data Collect', 'Collected File : 100527_0330_sgsnmit23_nbez25_1000_R04.txt', 'support_1', '');
INSERT INTO sys_log_ast VALUES ((select date ( now() )  - 2) || ' 18:22:47', 'Info', 'Trending&Aggregation_TU', 'Data Collect', 'Collected File : 100527_0330_sgsnmit23_nbez25_2000_69.txt', 'support_1', '');
INSERT INTO sys_log_ast VALUES ((select date ( now() )  - 2) || ' 18:22:48', 'Info', 'Trending&Aggregation_TU', 'Data Collect', 'PROCESS : End collecting files (192 files)', 'support_1', '');
INSERT INTO sys_log_ast VALUES ((select date ( now() )  - 2) || ' 18:25:07', 'Info', 'Trending&Aggregation_TU', 'Data Collect', 'PROCESS : Start Retrieve', 'support_1', '');
INSERT INTO sys_log_ast VALUES ((select date ( now() )  - 2) || ' 18:31:59', 'Warning', 'Trending&Aggregation_TU', 'Data Collect', 'No iu_RNC file for hour 2010052723', 'support_1', '');
INSERT INTO sys_log_ast VALUES ((select date ( now() )  - 2) || ' 18:36:42', 'Warning', 'Trending&Aggregation_TU', 'Data Collect', 'No iu_SVR file for hour 2010052700', 'support_1', '');
INSERT INTO sys_log_ast VALUES ((select date ( now() )  - 2) || ' 18:37:09', 'Info', 'Trending&Aggregation_TU', 'Data Collect', '391 Data Inserted for 2010052700 - Efficace/Paging/Timers SAI', 'support_1', '');
INSERT INTO sys_log_ast VALUES ((select date ( now() )  - 2) || ' 18:38:24', 'Info', 'Trending&Aggregation_TU', 'Data Collect', '118 Data Inserted for 2010052700 - APName', 'support_1', '');
INSERT INTO sys_log_ast VALUES ((select date ( now() )  - 2) || ' 18:38:40', 'Warning', 'Trending&Aggregation_TU', 'Data Collect', '0 Data Inserted for 2010052700 - Customized statistics per RNC', 'support_1', '');
INSERT INTO sys_log_ast VALUES ((select date ( now() )  - 2) || ' 18:39:11', 'Warning', 'Trending&Aggregation_TU', 'Data Collect', '0 Data Inserted for 2010052700 - PagingLAC', 'support_1', '');
INSERT INTO sys_log_ast VALUES ((select date ( now() )  - 2) || ' 18:39:35', 'Info', 'Trending&Aggregation_TU', 'Data Collect', '1 Data Inserted for 2010052700 - PagingRAC', 'support_1', '');
INSERT INTO sys_log_ast VALUES ((select date ( now() )  - 2) || ' 18:39:51', 'Info', 'Trending&Aggregation_TU', 'Data Collect', '57 Data Inserted for 2010052700 - Roamer', 'support_1', '');
INSERT INTO sys_log_ast VALUES ((select date ( now() )  - 2) || ' 18:40:08', 'Info', 'Trending&Aggregation_TU', 'Data Collect', '256 Data Inserted for 2010052700 - Handovers', 'support_1', '');
INSERT INTO sys_log_ast VALUES ((select date ( now() )  - 2) || ' 18:40:26', 'Info', 'Trending&Aggregation_TU', 'Data Collect', '1174 Data Inserted for 2010052700 - Traffic ToS', 'support_1', '');
INSERT INTO sys_log_ast VALUES ((select date ( now() )  - 2) || ' 18:41:22', 'Info', 'Trending&Aggregation_TU', 'Data Collect', '150 Data Inserted for 2010052700 - APName CoS', 'support_1', '');
INSERT INTO sys_log_ast VALUES ((select date ( now() )  - 2) || ' 18:41:43', 'Info', 'Trending&Aggregation_TU', 'Data Collect', '63 Data Inserted for 2010052700 - Qos HW', 'support_1', '');
INSERT INTO sys_log_ast VALUES ((select date ( now() )  - 2) || ' 18:42:05', 'Info', 'Trending&Aggregation_TU', 'Data Collect', '224 Data Inserted for 2010052700 - QoS Host', 'support_1', '');
INSERT INTO sys_log_ast VALUES ((select date ( now() )  - 2) || ' 18:44:27', 'Info', 'Trending&Aggregation_TU', 'Data Collect', 'PROCESS : End Retrieve', 'support_1', '');
INSERT INTO sys_log_ast VALUES ((select date ( now() )  - 2) || ' 18:45:35', 'Info', 'Trending&Aggregation_TU', 'Data Compute', 'PROCESS : Start Data Compute : 27- 05-2010', 'support_1', '');
INSERT INTO sys_log_ast VALUES ((select date ( now() )  - 2) || ' 18:47:27', 'Info', 'Trending&Aggregation_TU', 'Data Compute', 'Compute Raw Duration : 71.8 | 1 period(s)', 'support_1', '');
INSERT INTO sys_log_ast VALUES ((select date ( now() )  - 2) || ' 18:48:21', 'Info', 'Trending&Aggregation_TU', 'Data Compute', 'Compute KPI Duration : 49.5 | 1 period(s)', 'support_1', '');
INSERT INTO sys_log_ast VALUES ((select date ( now() )  - 2) || ' 18:49:09', 'Info', 'Trending&Aggregation_TU', '', 'Alarm CS call drop rate RNS CN (stam.0016.ept.00001) calculation time : 0.03 s, 1 period(s)', 'support_1', '');
INSERT INTO sys_log_ast VALUES ((select date ( now() )  - 2) || ' 18:49:09', 'Info', 'Trending&Aggregation_TU', '', 'Alarm CS call set-up inefficiency RNS CN (stam.0016.ept.00003) calculation time : 0.01 s, 1 period(s)', 'support_1', '');
INSERT INTO sys_log_ast VALUES ((select date ( now() )  - 2) || ' 18:49:10', 'Info', 'Trending&Aggregation_TU', '', 'Alarm Duration of call setup for CS calls (stam.0016.ept.00005) calculation time : 0.01 s, 1 period(s)', 'support_1', '');
INSERT INTO sys_log_ast VALUES ((select date ( now() )  - 2) || ' 18:49:10', 'Info', 'Trending&Aggregation_TU', '', 'Alarm Average duration of communications for CS Calls (stam.0016.ept.00006) calculation time : 0.01 s, 1 period(s)', 'support_1', '');
INSERT INTO sys_log_ast VALUES ((select date ( now() )  - 2) || ' 18:49:10', 'Info', 'Trending&Aggregation_TU', '', 'Alarm No PS traffic (stam.0016.ept.00007) calculation time : 0.02 s, 1 period(s)', 'support_1', '');
INSERT INTO sys_log_ast VALUES ((select date ( now() )  - 2) || ' 18:49:10', 'Info', 'Trending&Aggregation_TU', '', 'Alarm No CS traffic (stam.0016.ept.00008) calculation time : 0.05 s, 1 period(s)', 'support_1', '');
INSERT INTO sys_log_ast VALUES ((select date ( now() )  - 2) || ' 18:49:10', 'Info', 'Trending&Aggregation_TU', '', 'Alarm Bad Hourly CS call ineff SAI (stam.0016.ept.00009) calculation time : 0.02 s, 24 period(s)', 'support_1', '');
INSERT INTO sys_log_ast VALUES ((select date ( now() )  - 2) || ' 18:49:10', 'Info', 'Trending&Aggregation_TU', '', 'Alarm Bad hourly CS call drop SAI (stam.0016.ept.00011) calculation time : 0.02 s, 24 period(s)', 'support_1', '');
INSERT INTO sys_log_ast VALUES ((select date ( now() )  - 2) || ' 18:49:10', 'Info', 'Trending&Aggregation_TU', '', 'Alarm Avg PS Session Activation duration (stam.0016.ept.00013) calculation time : 0.01 s, 1 period(s)', 'support_1', '');
INSERT INTO sys_log_ast VALUES ((select date ( now() )  - 2) || ' 18:49:10', 'Info', 'Trending&Aggregation_TU', '', 'Alarm Call Number Increase (dyam.0016.ept.00001) calculation time : 0 s, 1 period(s)', 'support_1', '');
INSERT INTO sys_log_ast VALUES ((select date ( now() )  - 2) || ' 18:49:10', 'Info', 'Trending&Aggregation_TU', '', 'Alarm PS session Number Increase (dyam.0016.ept.00002) calculation time : 0 s, 1 period(s)', 'support_1', '');
INSERT INTO sys_log_ast VALUES ((select date ( now() )  - 2) || ' 18:49:10', 'Info', 'Trending&Aggregation_TU', '', 'Alarm High traffic CS SAI (towo.0008.01.00002) calculation time : 0.1 s, 1 period(s)', 'support_1', '');
INSERT INTO sys_log_ast VALUES ((select date ( now() )  - 2) || ' 18:49:10', 'Info', 'Trending&Aggregation_TU', '', 'Alarm High traffic PS SAI (towo.0008.01.00004) calculation time : 0.28 s, 1 period(s)', 'support_1', '');
INSERT INTO sys_log_ast VALUES ((select date ( now() )  - 2) || ' 18:49:10', 'Info', 'Trending&Aggregation_TU', '', 'Alarm High number of voice call drop due to RNS (towo.0008.01.00006) calculation time : 0.21 s, 1 period(s)', 'support_1', '');
INSERT INTO sys_log_ast VALUES ((select date ( now() )  - 2) || ' 19:15:23', 'Info', 'Trending&Aggregation_TU', '', 'Data Export (TestOJT) duration : 0.7', 'support_1', '');
INSERT INTO sys_log_ast VALUES ((select date ( now() )  - 2) || ' 19:15:02', 'Info', 'Trending&Aggregation_TU', '', 'Data Export (TestOJT) duration : 0.7', 'support_1', '');
INSERT INTO sys_log_ast VALUES ((select date ( now() )  - 2) || ' 19:14:42', 'Info', 'Trending&Aggregation_TU', '', 'Data Export (TestOJT) duration : 0.5', 'support_1', '');
INSERT INTO sys_log_ast VALUES ((select date ( now() )  - 2) || ' 19:14:09', 'Info', 'Trending&Aggregation_TU', '', 'Data Export (TestOJT) duration : 0.5', 'support_1', '');
INSERT INTO sys_log_ast VALUES ((select date ( now() )  - 2) || ' 19:13:07', 'Info', 'Trending&Aggregation_TU', '', 'Data Export (TestOJT) duration : 0.6', 'support_1', '');
INSERT INTO sys_log_ast VALUES ((select date ( now() )  - 2) || ' 19:11:07', 'Info', 'Trending&Aggregation_TU', '', 'Data Export (TestOJT) duration : 0.6', 'support_1', '');
INSERT INTO sys_log_ast VALUES ((select date ( now() )  - 2) || ' 19:10:49', 'Info', 'Trending&Aggregation_TU', '', 'Data Export (TestOJT) duration : 0.1', 'support_1', '');
INSERT INTO sys_log_ast VALUES ((select date ( now() )  - 1) || ' 18:21:16', 'Info', 'Trending&Aggregation_TU', 'Data Collect', 'PROCESS : Start collecting files', 'support_1', '');
INSERT INTO sys_log_ast VALUES ((select date ( now() )  - 1) || ' 18:21:17', 'Info', 'Trending&Aggregation_TU', 'Data Collect', 'Collected File : 100527_0330_sgsnmit23_nbez25_1000_R04.txt', 'support_1', '');
INSERT INTO sys_log_ast VALUES ((select date ( now() )  - 1) || ' 18:22:47', 'Info', 'Trending&Aggregation_TU', 'Data Collect', 'Collected File : 100527_0330_sgsnmit23_nbez25_2000_69.txt', 'support_1', '');
INSERT INTO sys_log_ast VALUES ((select date ( now() )  - 1) || ' 18:22:48', 'Info', 'Trending&Aggregation_TU', 'Data Collect', 'PROCESS : End collecting files (192 files)', 'support_1', '');
INSERT INTO sys_log_ast VALUES ((select date ( now() )  - 1) || ' 18:25:07', 'Info', 'Trending&Aggregation_TU', 'Data Collect', 'PROCESS : Start Retrieve', 'support_1', '');
INSERT INTO sys_log_ast VALUES ((select date ( now() )  - 1) || ' 18:31:59', 'Warning', 'Trending&Aggregation_TU', 'Data Collect', 'No iu_RNC file for hour 2010052723', 'support_1', '');
INSERT INTO sys_log_ast VALUES ((select date ( now() )  - 1) || ' 18:36:42', 'Warning', 'Trending&Aggregation_TU', 'Data Collect', 'No iu_SVR file for hour 2010052700', 'support_1', '');
INSERT INTO sys_log_ast VALUES ((select date ( now() )  - 1) || ' 18:37:09', 'Info', 'Trending&Aggregation_TU', 'Data Collect', '391 Data Inserted for 2010052700 - Efficace/Paging/Timers SAI', 'support_1', '');
INSERT INTO sys_log_ast VALUES ((select date ( now() )  - 1) || ' 18:38:24', 'Info', 'Trending&Aggregation_TU', 'Data Collect', '118 Data Inserted for 2010052700 - APName', 'support_1', '');
INSERT INTO sys_log_ast VALUES ((select date ( now() )  - 1) || ' 18:38:40', 'Warning', 'Trending&Aggregation_TU', 'Data Collect', '0 Data Inserted for 2010052700 - Customized statistics per RNC', 'support_1', '');
INSERT INTO sys_log_ast VALUES ((select date ( now() )  - 1) || ' 18:39:11', 'Warning', 'Trending&Aggregation_TU', 'Data Collect', '0 Data Inserted for 2010052700 - PagingLAC', 'support_1', '');
INSERT INTO sys_log_ast VALUES ((select date ( now() )  - 1) || ' 18:39:35', 'Info', 'Trending&Aggregation_TU', 'Data Collect', '1 Data Inserted for 2010052700 - PagingRAC', 'support_1', '');
INSERT INTO sys_log_ast VALUES ((select date ( now() )  - 1) || ' 18:39:51', 'Info', 'Trending&Aggregation_TU', 'Data Collect', '57 Data Inserted for 2010052700 - Roamer', 'support_1', '');
INSERT INTO sys_log_ast VALUES ((select date ( now() )  - 1) || ' 18:40:08', 'Info', 'Trending&Aggregation_TU', 'Data Collect', '256 Data Inserted for 2010052700 - Handovers', 'support_1', '');
INSERT INTO sys_log_ast VALUES ((select date ( now() )  - 1) || ' 18:40:26', 'Info', 'Trending&Aggregation_TU', 'Data Collect', '1174 Data Inserted for 2010052700 - Traffic ToS', 'support_1', '');
INSERT INTO sys_log_ast VALUES ((select date ( now() )  - 1) || ' 18:41:22', 'Info', 'Trending&Aggregation_TU', 'Data Collect', '150 Data Inserted for 2010052700 - APName CoS', 'support_1', '');
INSERT INTO sys_log_ast VALUES ((select date ( now() )  - 1) || ' 18:41:43', 'Info', 'Trending&Aggregation_TU', 'Data Collect', '63 Data Inserted for 2010052700 - Qos HW', 'support_1', '');
INSERT INTO sys_log_ast VALUES ((select date ( now() )  - 1) || ' 18:42:05', 'Info', 'Trending&Aggregation_TU', 'Data Collect', '224 Data Inserted for 2010052700 - QoS Host', 'support_1', '');
INSERT INTO sys_log_ast VALUES ((select date ( now() )  - 1) || ' 18:44:27', 'Info', 'Trending&Aggregation_TU', 'Data Collect', 'PROCESS : End Retrieve', 'support_1', '');
INSERT INTO sys_log_ast VALUES ((select date ( now() )  - 1) || ' 18:45:35', 'Info', 'Trending&Aggregation_TU', 'Data Compute', 'PROCESS : Start Data Compute : 27- 05-2010', 'support_1', '');
INSERT INTO sys_log_ast VALUES ((select date ( now() )  - 1) || ' 18:47:27', 'Info', 'Trending&Aggregation_TU', 'Data Compute', 'Compute Raw Duration : 71.8 | 1 period(s)', 'support_1', '');
INSERT INTO sys_log_ast VALUES ((select date ( now() )  - 1) || ' 18:48:21', 'Info', 'Trending&Aggregation_TU', 'Data Compute', 'Compute KPI Duration : 49.5 | 1 period(s)', 'support_1', '');
INSERT INTO sys_log_ast VALUES ((select date ( now() )  - 1) || ' 18:49:09', 'Info', 'Trending&Aggregation_TU', '', 'Alarm CS call drop rate RNS CN (stam.0016.ept.00001) calculation time : 0.03 s, 1 period(s)', 'support_1', '');
INSERT INTO sys_log_ast VALUES ((select date ( now() )  - 1) || ' 18:49:09', 'Info', 'Trending&Aggregation_TU', '', 'Alarm CS call set-up inefficiency RNS CN (stam.0016.ept.00003) calculation time : 0.01 s, 1 period(s)', 'support_1', '');
INSERT INTO sys_log_ast VALUES ((select date ( now() )  - 1) || ' 18:49:10', 'Info', 'Trending&Aggregation_TU', '', 'Alarm Duration of call setup for CS calls (stam.0016.ept.00005) calculation time : 0.01 s, 1 period(s)', 'support_1', '');
INSERT INTO sys_log_ast VALUES ((select date ( now() )  - 1) || ' 18:49:10', 'Info', 'Trending&Aggregation_TU', '', 'Alarm Average duration of communications for CS Calls (stam.0016.ept.00006) calculation time : 0.01 s, 1 period(s)', 'support_1', '');
INSERT INTO sys_log_ast VALUES ((select date ( now() )  - 1) || ' 18:49:10', 'Info', 'Trending&Aggregation_TU', '', 'Alarm No PS traffic (stam.0016.ept.00007) calculation time : 0.02 s, 1 period(s)', 'support_1', '');
INSERT INTO sys_log_ast VALUES ((select date ( now() )  - 1) || ' 18:49:10', 'Info', 'Trending&Aggregation_TU', '', 'Alarm No CS traffic (stam.0016.ept.00008) calculation time : 0.05 s, 1 period(s)', 'support_1', '');
INSERT INTO sys_log_ast VALUES ((select date ( now() )  - 1) || ' 18:49:10', 'Info', 'Trending&Aggregation_TU', '', 'Alarm Bad Hourly CS call ineff SAI (stam.0016.ept.00009) calculation time : 0.02 s, 24 period(s)', 'support_1', '');
INSERT INTO sys_log_ast VALUES ((select date ( now() )  - 1) || ' 18:49:10', 'Info', 'Trending&Aggregation_TU', '', 'Alarm Bad hourly CS call drop SAI (stam.0016.ept.00011) calculation time : 0.02 s, 24 period(s)', 'support_1', '');
INSERT INTO sys_log_ast VALUES ((select date ( now() )  - 1) || ' 18:49:10', 'Info', 'Trending&Aggregation_TU', '', 'Alarm Avg PS Session Activation duration (stam.0016.ept.00013) calculation time : 0.01 s, 1 period(s)', 'support_1', '');
INSERT INTO sys_log_ast VALUES ((select date ( now() )  - 1) || ' 18:49:10', 'Info', 'Trending&Aggregation_TU', '', 'Alarm Call Number Increase (dyam.0016.ept.00001) calculation time : 0 s, 1 period(s)', 'support_1', '');
INSERT INTO sys_log_ast VALUES ((select date ( now() )  - 1) || ' 18:49:10', 'Info', 'Trending&Aggregation_TU', '', 'Alarm PS session Number Increase (dyam.0016.ept.00002) calculation time : 0 s, 1 period(s)', 'support_1', '');
INSERT INTO sys_log_ast VALUES ((select date ( now() )  - 1) || ' 18:49:10', 'Info', 'Trending&Aggregation_TU', '', 'Alarm High traffic CS SAI (towo.0008.01.00002) calculation time : 0.1 s, 1 period(s)', 'support_1', '');
INSERT INTO sys_log_ast VALUES ((select date ( now() )  - 1) || ' 18:49:10', 'Info', 'Trending&Aggregation_TU', '', 'Alarm High traffic PS SAI (towo.0008.01.00004) calculation time : 0.28 s, 1 period(s)', 'support_1', '');
INSERT INTO sys_log_ast VALUES ((select date ( now() )  - 1) || ' 18:49:10', 'Info', 'Trending&Aggregation_TU', '', 'Alarm High number of voice call drop due to RNS (towo.0008.01.00006) calculation time : 0.21 s, 1 period(s)', 'support_1', '');
INSERT INTO sys_log_ast VALUES ((select date ( now() )  - 1) || ' 19:15:23', 'Info', 'Trending&Aggregation_TU', '', 'Data Export (TestOJT) duration : 0.7', 'support_1', '');
INSERT INTO sys_log_ast VALUES ((select date ( now() )  - 1) || ' 19:15:02', 'Info', 'Trending&Aggregation_TU', '', 'Data Export (TestOJT) duration : 0.7', 'support_1', '');
INSERT INTO sys_log_ast VALUES ((select date ( now() )  - 1) || ' 19:14:42', 'Info', 'Trending&Aggregation_TU', '', 'Data Export (TestOJT) duration : 0.5', 'support_1', '');
INSERT INTO sys_log_ast VALUES ((select date ( now() )  - 1) || ' 19:14:09', 'Info', 'Trending&Aggregation_TU', '', 'Data Export (TestOJT) duration : 0.5', 'support_1', '');
INSERT INTO sys_log_ast VALUES ((select date ( now() )  - 1) || ' 19:13:07', 'Info', 'Trending&Aggregation_TU', '', 'Data Export (TestOJT) duration : 0.6', 'support_1', '');
INSERT INTO sys_log_ast VALUES ((select date ( now() )  - 1) || ' 19:11:07', 'Info', 'Trending&Aggregation_TU', '', 'Data Export (TestOJT) duration : 0.6', 'support_1', '');
INSERT INTO sys_log_ast VALUES ((select date ( now() )  - 1) || ' 19:10:49', 'Info', 'Trending&Aggregation_TU', '', 'Data Export (TestOJT) duration : 0.1', 'support_1', '');
INSERT INTO sys_log_ast VALUES ((select date ( now() )  - 0) || ' 18:21:16', 'Info', 'Trending&Aggregation_TU', 'Data Collect', 'PROCESS : Start collecting files', 'support_1', '');
INSERT INTO sys_log_ast VALUES ((select date ( now() )  - 0) || ' 18:21:17', 'Info', 'Trending&Aggregation_TU', 'Data Collect', 'Collected File : 100527_0330_sgsnmit23_nbez25_1000_R04.txt', 'support_1', '');
INSERT INTO sys_log_ast VALUES ((select date ( now() )  - 0) || ' 18:22:47', 'Info', 'Trending&Aggregation_TU', 'Data Collect', 'Collected File : 100527_0330_sgsnmit23_nbez25_2000_69.txt', 'support_1', '');
INSERT INTO sys_log_ast VALUES ((select date ( now() )  - 0) || ' 18:22:48', 'Info', 'Trending&Aggregation_TU', 'Data Collect', 'PROCESS : End collecting files (192 files)', 'support_1', '');
INSERT INTO sys_log_ast VALUES ((select date ( now() )  - 0) || ' 18:25:07', 'Info', 'Trending&Aggregation_TU', 'Data Collect', 'PROCESS : Start Retrieve', 'support_1', '');
INSERT INTO sys_log_ast VALUES ((select date ( now() )  - 0) || ' 18:31:59', 'Warning', 'Trending&Aggregation_TU', 'Data Collect', 'No iu_RNC file for hour 2010052723', 'support_1', '');
INSERT INTO sys_log_ast VALUES ((select date ( now() )  - 0) || ' 18:36:42', 'Warning', 'Trending&Aggregation_TU', 'Data Collect', 'No iu_SVR file for hour 2010052700', 'support_1', '');
INSERT INTO sys_log_ast VALUES ((select date ( now() )  - 0) || ' 18:37:09', 'Info', 'Trending&Aggregation_TU', 'Data Collect', '391 Data Inserted for 2010052700 - Efficace/Paging/Timers SAI', 'support_1', '');
INSERT INTO sys_log_ast VALUES ((select date ( now() )  - 0) || ' 18:38:24', 'Info', 'Trending&Aggregation_TU', 'Data Collect', '118 Data Inserted for 2010052700 - APName', 'support_1', '');
INSERT INTO sys_log_ast VALUES ((select date ( now() )  - 0) || ' 18:38:40', 'Warning', 'Trending&Aggregation_TU', 'Data Collect', '0 Data Inserted for 2010052700 - Customized statistics per RNC', 'support_1', '');
INSERT INTO sys_log_ast VALUES ((select date ( now() )  - 0) || ' 18:39:11', 'Warning', 'Trending&Aggregation_TU', 'Data Collect', '0 Data Inserted for 2010052700 - PagingLAC', 'support_1', '');
INSERT INTO sys_log_ast VALUES ((select date ( now() )  - 0) || ' 18:39:35', 'Info', 'Trending&Aggregation_TU', 'Data Collect', '1 Data Inserted for 2010052700 - PagingRAC', 'support_1', '');
INSERT INTO sys_log_ast VALUES ((select date ( now() )  - 0) || ' 18:39:51', 'Info', 'Trending&Aggregation_TU', 'Data Collect', '57 Data Inserted for 2010052700 - Roamer', 'support_1', '');
INSERT INTO sys_log_ast VALUES ((select date ( now() )  - 0) || ' 18:40:08', 'Info', 'Trending&Aggregation_TU', 'Data Collect', '256 Data Inserted for 2010052700 - Handovers', 'support_1', '');
INSERT INTO sys_log_ast VALUES ((select date ( now() )  - 0) || ' 18:40:26', 'Info', 'Trending&Aggregation_TU', 'Data Collect', '1174 Data Inserted for 2010052700 - Traffic ToS', 'support_1', '');
INSERT INTO sys_log_ast VALUES ((select date ( now() )  - 0) || ' 18:41:22', 'Info', 'Trending&Aggregation_TU', 'Data Collect', '150 Data Inserted for 2010052700 - APName CoS', 'support_1', '');
INSERT INTO sys_log_ast VALUES ((select date ( now() )  - 0) || ' 18:41:43', 'Info', 'Trending&Aggregation_TU', 'Data Collect', '63 Data Inserted for 2010052700 - Qos HW', 'support_1', '');
INSERT INTO sys_log_ast VALUES ((select date ( now() )  - 0) || ' 18:42:05', 'Info', 'Trending&Aggregation_TU', 'Data Collect', '224 Data Inserted for 2010052700 - QoS Host', 'support_1', '');
INSERT INTO sys_log_ast VALUES ((select date ( now() )  - 0) || ' 18:44:27', 'Info', 'Trending&Aggregation_TU', 'Data Collect', 'PROCESS : End Retrieve', 'support_1', '');
INSERT INTO sys_log_ast VALUES ((select date ( now() )  - 0) || ' 18:45:35', 'Info', 'Trending&Aggregation_TU', 'Data Compute', 'PROCESS : Start Data Compute : 27- 05-2010', 'support_1', '');
INSERT INTO sys_log_ast VALUES ((select date ( now() )  - 0) || ' 18:47:27', 'Info', 'Trending&Aggregation_TU', 'Data Compute', 'Compute Raw Duration : 71.8 | 1 period(s)', 'support_1', '');
INSERT INTO sys_log_ast VALUES ((select date ( now() )  - 0) || ' 18:48:21', 'Info', 'Trending&Aggregation_TU', 'Data Compute', 'Compute KPI Duration : 49.5 | 1 period(s)', 'support_1', '');
INSERT INTO sys_log_ast VALUES ((select date ( now() )  - 0) || ' 18:49:09', 'Info', 'Trending&Aggregation_TU', '', 'Alarm CS call drop rate RNS CN (stam.0016.ept.00001) calculation time : 0.03 s, 1 period(s)', 'support_1', '');
INSERT INTO sys_log_ast VALUES ((select date ( now() )  - 0) || ' 18:49:09', 'Info', 'Trending&Aggregation_TU', '', 'Alarm CS call set-up inefficiency RNS CN (stam.0016.ept.00003) calculation time : 0.01 s, 1 period(s)', 'support_1', '');
INSERT INTO sys_log_ast VALUES ((select date ( now() )  - 0) || ' 18:49:10', 'Info', 'Trending&Aggregation_TU', '', 'Alarm Duration of call setup for CS calls (stam.0016.ept.00005) calculation time : 0.01 s, 1 period(s)', 'support_1', '');
INSERT INTO sys_log_ast VALUES ((select date ( now() )  - 0) || ' 18:49:10', 'Info', 'Trending&Aggregation_TU', '', 'Alarm Average duration of communications for CS Calls (stam.0016.ept.00006) calculation time : 0.01 s, 1 period(s)', 'support_1', '');
INSERT INTO sys_log_ast VALUES ((select date ( now() )  - 0) || ' 18:49:10', 'Info', 'Trending&Aggregation_TU', '', 'Alarm No PS traffic (stam.0016.ept.00007) calculation time : 0.02 s, 1 period(s)', 'support_1', '');
INSERT INTO sys_log_ast VALUES ((select date ( now() )  - 0) || ' 18:49:10', 'Info', 'Trending&Aggregation_TU', '', 'Alarm No CS traffic (stam.0016.ept.00008) calculation time : 0.05 s, 1 period(s)', 'support_1', '');
INSERT INTO sys_log_ast VALUES ((select date ( now() )  - 0) || ' 18:49:10', 'Info', 'Trending&Aggregation_TU', '', 'Alarm Bad Hourly CS call ineff SAI (stam.0016.ept.00009) calculation time : 0.02 s, 24 period(s)', 'support_1', '');
INSERT INTO sys_log_ast VALUES ((select date ( now() )  - 0) || ' 18:49:10', 'Info', 'Trending&Aggregation_TU', '', 'Alarm Bad hourly CS call drop SAI (stam.0016.ept.00011) calculation time : 0.02 s, 24 period(s)', 'support_1', '');
INSERT INTO sys_log_ast VALUES ((select date ( now() )  - 0) || ' 18:49:10', 'Info', 'Trending&Aggregation_TU', '', 'Alarm Avg PS Session Activation duration (stam.0016.ept.00013) calculation time : 0.01 s, 1 period(s)', 'support_1', '');
INSERT INTO sys_log_ast VALUES ((select date ( now() )  - 0) || ' 18:49:10', 'Info', 'Trending&Aggregation_TU', '', 'Alarm Call Number Increase (dyam.0016.ept.00001) calculation time : 0 s, 1 period(s)', 'support_1', '');
INSERT INTO sys_log_ast VALUES ((select date ( now() )  - 0) || ' 18:49:10', 'Info', 'Trending&Aggregation_TU', '', 'Alarm PS session Number Increase (dyam.0016.ept.00002) calculation time : 0 s, 1 period(s)', 'support_1', '');
INSERT INTO sys_log_ast VALUES ((select date ( now() )  - 0) || ' 18:49:10', 'Info', 'Trending&Aggregation_TU', '', 'Alarm High traffic CS SAI (towo.0008.01.00002) calculation time : 0.1 s, 1 period(s)', 'support_1', '');
INSERT INTO sys_log_ast VALUES ((select date ( now() )  - 0) || ' 18:49:10', 'Info', 'Trending&Aggregation_TU', '', 'Alarm High traffic PS SAI (towo.0008.01.00004) calculation time : 0.28 s, 1 period(s)', 'support_1', '');
INSERT INTO sys_log_ast VALUES ((select date ( now() )  - 0) || ' 18:49:10', 'Info', 'Trending&Aggregation_TU', '', 'Alarm High number of voice call drop due to RNS (towo.0008.01.00006) calculation time : 0.21 s, 1 period(s)', 'support_1', '');
INSERT INTO sys_log_ast VALUES ((select date ( now() )  - 0) || ' 19:15:23', 'Info', 'Trending&Aggregation_TU', 'Data Compute', 'Test base64 !', '');
INSERT INTO sys_log_ast VALUES ((select date ( now() )  - 0) || ' 19:15:23', 'Info', 'Trending&Aggregation_TU', '', 'Data Export (TestOJT) duration : 0.7', 'support_1', '');
INSERT INTO sys_log_ast VALUES ((select date ( now() )  - 0) || ' 19:15:02', 'Info', 'Trending&Aggregation_TU', '', 'Data Export (TestOJT) duration : 0.7', 'support_1', '');
INSERT INTO sys_log_ast VALUES ((select date ( now() )  - 0) || ' 19:14:42', 'Info', 'Trending&Aggregation_TU', '', 'Data Export (TestOJT) duration : 0.5', 'support_1', '');
INSERT INTO sys_log_ast VALUES ((select date ( now() )  - 0) || ' 19:14:09', 'Info', 'Trending&Aggregation_TU', '', 'Data Export (TestOJT) duration : 0.5', 'support_1', '');
INSERT INTO sys_log_ast VALUES ((select date ( now() )  - 0) || ' 19:13:07', 'Info', 'Trending&Aggregation_TU', '', 'Data Export (TestOJT) duration : 0.6', 'support_1', '');
INSERT INTO sys_log_ast VALUES ((select date ( now() )  - 0) || ' 19:11:07', 'Info', 'Trending&Aggregation_TU', '', 'Data Export (TestOJT) duration : 0.6', 'support_1', '');
INSERT INTO sys_log_ast VALUES ((select date ( now() )  - 0) || ' 19:10:49', 'Info', 'Trending&Aggregation_TU', '', 'Data Export (TestOJT) duration : 0.1', 'support_1', '');

TRUNCATE TABLE sys_definition_alarm_static;
INSERT INTO sys_definition_alarm_static VALUES ('sdas.7d1257f31afa34567dd173321f46fe15', 'Alarm1_TU', 'AT_Cn', '>', 'raw', 1, 'sai', 'day', NULL, 'ept', 1, NULL, 'customisateur', NULL, NULL, NULL, 'critical', 1, 1, 1);
INSERT INTO sys_definition_alarm_static VALUES ('sdas.32352875ce41b1843708bb0d1d8efb74', 'Alarm2_TU', 'AT_Cn', '=', 'raw', 1, 'sai', 'hour', NULL, 'ept', 0, NULL, 'customisateur', NULL, NULL, NULL, 'critical', 1, 1, 1);

TRUNCATE TABLE sys_definition_alarm_dynamic;
INSERT INTO sys_definition_alarm_dynamic VALUES ('sdad.7484932b20bb6d8d3fca963f1ee94104', 'Dyn1_TU', 'AA', 'kpi', 10, 'sai', NULL, NULL, 'day', 1, NULL, 'ept', 14, NULL, 0, NULL, 'customisateur', 'AA', 'kpi', '=', 0, NULL, 'critical', 1, 1, 1);

TRUNCATE TABLE sys_definition_alarm_top_worst;
INSERT INTO sys_definition_alarm_top_worst VALUES ('sdatw.e46359e2439dc7b5c307802a7ce65d83', 'TW1_TU', 'AT_Cn', 'asc', 1, 'lac', 'raw', NULL, NULL, 'hour', NULL, 'ept', NULL, 'customisateur', 'AT_Cn', 'raw', '=', 0, NULL, 1, 1, 1);
INSERT INTO sys_definition_alarm_top_worst VALUES ('sdatw.f9d355ae0f240002f2840e1328d2094a', 'TW3_TU', 'BZ16774', 'asc', 1, 'sai', 'kpi', NULL, NULL, 'hour', NULL, 'ept', NULL, 'customisateur', 'AT_Cn_REJ_IENEorNI', 'raw', '=', 2, NULL, 1, 1, 1);
INSERT INTO sys_definition_alarm_top_worst VALUES ('sdatw.2365d9c89ddc0fd1561cb85095b78208', 'TW2_TU', 'AT_Ms_REJ_PLMNNA', 'asc', 1, 'lac', 'raw', NULL, NULL, 'month', NULL, 'ept', NULL, 'customisateur', 'AT_Ms_REJ_ILLEMS', 'raw', '<=', 100, NULL, 1, 1, 1);
